version: '3'
services:
  app:
    build:
      context: .
    ports:
      - ${APP_PORT}:3000
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: "postgres:14.5"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    tty: true
    ports:
      - ${DB_PORT}:5432
